version: "3"
services:
  dev:
    # build from Dockerfile in current directory
    image: node:10
    # bind mount current directory on host to /me-site on container
    volumes:
      - .:/projects/me-site
    # where the command will be run
    working_dir: /projects/me-site
    # command to start the dev server
    command: >
      bash -c "npm rebuild node-sass 
      && npm install
      && npm start"
    # maps host port to container port
    ports:
      - "8888:8888"
      - "8443:8443"